development:
  adapter: postgresql
  encoding: utf8
  database: chop_chop_edu
  host: localhost
  pool: 5
  username: postgres
  password: admin

test:
  adapter: postgresql
  encoding: utf8
  database: chop_chop_edu_test
  host: localhost
  pool: 5
  username: postgres
  password: admin